name: LinkedIn Opportunity Monitor

on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test LinkedIn Agent
      run: |
        python linkedin_agent.py
        
    - name: Save Results
      run: |
        echo "Agent test completed on $(date)" >> test_log.txt
        echo "✅ Test results saved to test_log.txt"
        cat test_log.txt
